[meta]
committer_name = "Mergebot 9000"
committer_email = "git@eaxample.com"

[local]
path = "/some/local/path"
target_branch = "deploy"
upstream_base = "upstream/master"

[remote.github]
interface_class = "Buildotron::Remote::Github"
api_url = "https://api.github.com"
api_key = "your-api-key"
repo = "mmcclimon/rustmergency"

[remote.gitlab]
interface_class = "Buildotron::Remote::GitLab"
api_url = "https://gitlab.com/api/v4"
api_key = "ENV:GITLAB_API_KEY"
repo = "mmcclimon/rustmergency"

[[build_steps]]
name = "upstream"
remote = "github"
label = "include-in-deploy"
tag_format = "mergebot-%d.%s"

[[build_steps]]
name = "local"
remote = "gitlab"
label = "include-in-deploy"
tag_format = "mergebot-local-%d.%s-fastmail"
